variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  KUBE_INGRESS_BASE_DOMAIN: nonprod.tower.cdrentertainment.com
  HELM_SCALE_EXTRA_ARGS: --set postgresql.enabled="false" 
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  

stages:
  - eng
  - prod

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always


eng:
  stage: eng
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
  script:
    - |
        for f in ./*.json; do
          FN=${f%.*};
          TXT=$(cat "${FN}.txt");
          HTML=$(cat "${FN}.html");
          SBJ=$(head -n 1 "${FN}.txt" | tail -c +6 | head -c -5);
          sed -i "s/__subject__/`echo $SBJ`/g" $f;
          sed -i "s/__text__/`echo $TXT`/g" $f;
          sed -i "s,__html__,`echo $HTML`,g" $f;
          cat $f
          aws ses create-template --cli-input-json file://$f --region us-east-1
        done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always



