variables:
  # KUBE_INGRESS_BASE_DOMAIN is the application deployment domain and should be set as a variable at the group or project level.
  KUBE_INGRESS_BASE_DOMAIN: nonprod.tower.cdrentertainment.com
  HELM_SCALE_EXTRA_ARGS: --set postgresql.enabled="false" 
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  JSON: ./upload_template.json
  TEMPLATE_CONTENT: '{"Template":{"TemplateName":"__name__","SubjectPart":"__subject__","HtmlPart":"__html__","TextPart":"__text__"}}'

stages:
  - dev
  - stage
  - prod
  - danger-zone

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

local:
  stage: dev
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: "007"
  script:
    - |
      for f in ./*.html; do
        FILENAME=${f%.*};
        sed -i "s/\"/'/g" ${FILENAME}.txt;
        sed -i "s/\"/'/g" ${FILENAME}.html;
      
        NAME=${f:2};
        TEXT=$(cat "${FILENAME}.txt");
        HTML=$(cat "${FILENAME}.html");
        SUBJECT=$(head -n 1 "${FILENAME}.html" | tail -c +6 | head -c -5);
      
        echo $TEMPLATE_CONTENT > $JSON;
        sed -i "s/__name__/`echo $ENV-$FILENAME`/g" $JSON;
        sed -i "s/__subject__/`echo $SUBJECT`/g" $JSON;
        sed -i "s/__text__/`echo $TEXT`/g" $JSON;
        sed -i "s,__html__,`echo $HTML`,g" $JSON;
        cat $JSON
        aws ses update-template --cli-input-json file://$JSON --region us-east-1 || aws ses create-template --cli-input-json file://$JSON --region us-east-1
        sleep 3
      done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

dev:
  stage: dev
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: 107
  script:
    - |
        for f in ./*.html; do
          FILENAME=${f%.*};
          sed -i "s/\"/'/g" ${FILENAME}.txt;
          sed -i "s/\"/'/g" ${FILENAME}.html;
      
          NAME=${f:2};
          TEXT=$(cat "${FILENAME}.txt");
          HTML=$(cat "${FILENAME}.html");
          SUBJECT=$(head -n 1 "${FILENAME}.html" | tail -c +6 | head -c -5);
      
          echo $TEMPLATE_CONTENT > $JSON;
          sed -i "s/__name__/`echo $ENV-$FILENAME`/g" $JSON;
          sed -i "s/__subject__/`echo $SUBJECT`/g" $JSON;
          sed -i "s/__text__/`echo $TEXT`/g" $JSON;
          sed -i "s,__html__,`echo $HTML`,g" $JSON;
          cat $JSON
          aws ses update-template --cli-input-json file://$JSON --region us-east-1 || aws ses create-template --cli-input-json file://$JSON --region us-east-1
          sleep 3
        done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual
      
stage-a:
  stage: stage
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: 207
  script:
    - |
      for f in ./*.html; do
        FILENAME=${f%.*};
        sed -i "s/\"/'/g" ${FILENAME}.txt;
        sed -i "s/\"/'/g" ${FILENAME}.html;
      
        NAME=${f:2};
        TEXT=$(cat "${FILENAME}.txt");
        HTML=$(cat "${FILENAME}.html");
        SUBJECT=$(head -n 1 "${FILENAME}.html" | tail -c +6 | head -c -5);
      
        echo $TEMPLATE_CONTENT > $JSON;
        sed -i "s/__name__/`echo $ENV-$NAME`/g" $JSON;
        sed -i "s/__subject__/`echo $SUBJECT`/g" $JSON;
        sed -i "s/__text__/`echo $TEXT`/g" $JSON;
        sed -i "s,__html__,`echo $HTML`,g" $JSON;
        cat $JSON
        aws ses update-template --cli-input-json file://$JSON --region us-east-1 || aws ses create-template --cli-input-json file://$JSON --region us-east-1
        sleep 3
      done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual
      
stage-b:
  stage: stage
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: 217
  script:
    - |
      for f in ./*.html; do
        FILENAME=${f%.*};
        sed -i "s/\"/'/g" ${FILENAME}.txt;
        sed -i "s/\"/'/g" ${FILENAME}.html;
      
        NAME=${f:2};
        TEXT=$(cat "${FILENAME}.txt");
        HTML=$(cat "${FILENAME}.html");
        SUBJECT=$(head -n 1 "${FILENAME}.html" | tail -c +6 | head -c -5);
      
        echo $TEMPLATE_CONTENT > $JSON;
        sed -i "s/__name__/`echo $ENV-$NAME`/g" $JSON;
        sed -i "s/__subject__/`echo $SUBJECT`/g" $JSON;
        sed -i "s/__text__/`echo $TEXT`/g" $JSON;
        sed -i "s,__html__,`echo $HTML`,g" $JSON;
        cat $JSON
        aws ses update-template --cli-input-json file://$JSON --region us-east-1 || aws ses create-template --cli-input-json file://$JSON --region us-east-1
        sleep 3
      done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual

stage-c:
  stage: stage
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: 227
  script:
    - |
      for f in ./*.html; do
        FILENAME=${f%.*};
        sed -i "s/\"/'/g" ${FILENAME}.txt;
        sed -i "s/\"/'/g" ${FILENAME}.html;
      
        NAME=${f:2};
        TEXT=$(cat "${FILENAME}.txt");
        HTML=$(cat "${FILENAME}.html");
        SUBJECT=$(head -n 1 "${FILENAME}.html" | tail -c +6 | head -c -5);
      
        echo $TEMPLATE_CONTENT > $JSON;
        sed -i "s/__name__/`echo $ENV-$NAME`/g" $JSON;
        sed -i "s/__subject__/`echo $SUBJECT`/g" $JSON;
        sed -i "s/__text__/`echo $TEXT`/g" $JSON;
        sed -i "s,__html__,`echo $HTML`,g" $JSON;
        cat $JSON
        aws ses update-template --cli-input-json file://$JSON --region us-east-1 || aws ses create-template --cli-input-json file://$JSON --region us-east-1
        sleep 3
      done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual
      
prod-a1/a2:
  stage: prod
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: 308
  script:
    - |
      for f in ./*.html; do
        FILENAME=${f%.*};
        sed -i "s/\"/'/g" ${FILENAME}.txt;
        sed -i "s/\"/'/g" ${FILENAME}.html;
      
        NAME=${f:2};
        TEXT=$(cat "${FILENAME}.txt");
        HTML=$(cat "${FILENAME}.html");
        SUBJECT=$(head -n 1 "${FILENAME}.html" | tail -c +6 | head -c -5);
      
        echo $TEMPLATE_CONTENT > $JSON;
        sed -i "s/__name__/`echo $ENV-$NAME`/g" $JSON;
        sed -i "s/__subject__/`echo $SUBJECT`/g" $JSON;
        sed -i "s/__text__/`echo $TEXT`/g" $JSON;
        sed -i "s,__html__,`echo $HTML`,g" $JSON;
        cat $JSON
        aws ses update-template --cli-input-json file://$JSON --region us-east-1 || aws ses create-template --cli-input-json file://$JSON --region us-east-1
        sleep 3
      done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual

delete-dev:
  stage: danger-zone
  image: amazon/aws-cli
  tags:
    - kubernetes
  variables:
    AWS_ACCESS_KEY_ID: $ACCESS_KEY #still needs to be created
    AWS_SECRET_ACCESS_KEY: $ACCESS_KEY_SECRET
    ENV: 107
  script:
    - |
      for f in ./*.json; do
        FN=${f%.*};
        echo aws ses delete-template --template-name $ENV-${FN:2} --region us-east-1
      done
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: manual